const lang={
    HeadAttack : `Head-Attack`,
    BowSpeed : `Bow-Speed`,
    Include : `Include`,
    HandleTraits : `Handle-Traits`,
    Filt : `Search`,
    String : `String`,
    Name : `Name`,
    CoreTraits : `Core-Traits`,
    BowRange : `Bow-Range`,
    HeadDurability : `Head-Durability`,
    PlateModifier : `Plate-Modifier`,
    FletchingAccuracy : `Fletching-Accuracy`,
    MiningSpeed : `Mining Speed`,
    DataSourceEnvironment : `Data Source Environment`,
    Search : `Search`,
    Shaft : `Shaft`,
    HeadSpeed : `Head-Mining Speed`,
    CoreDurability : `Core-Durability`,
    Compare : `Chart`,
    StringTraits : `String-Traits`,
    PlateDurability : `Plate-Durability`,
    NoFilters : `No Filters`,
    Core : `Core`,
    HandleDurability : `Handle-Durability`,
    ShaftTraits : `Shaft-Traits`,
    NonEqual : `Not Equal`,
    Head : `Head`,
    ExtraDurability : `Extra-Durability`,
    Local : `Local`,
    Durability : `Durability`,
    DataSourceInformation : `Data Source Information`,
    Bow : `Bow`,
    ExperimentalFeaturesWarning : `The following functions can cause performance problems when the amount of data is large`,
    Range : `Range`,
    FletchingModifier : `Fletching-Modifier`,
    About : `About`,
    DataSource : `Data Source`,
    Handle : `Handle`,
    Intro2 : `After generation is complete, you can uninstall Tinkers' Exporter, this does not influence the running of this application. If you don't uninstall, a exporting is done every time you start the game.`,
    HeadLevel : `Head-Mining Level`,
    PlateTraits : `Plate-Traits`,
    Intro3 : `This application can be used offline. You can rename and move the generated application directory, but DO NOT change the file name of the resource file or move out of the same directory, otherwise the application will not start properly.`,
    Intro1 : `This static single page application is generated and exported automatically according to the mods installed in your game. All data is stored locally only.`,
    AllMaterials : `All Mateirals`,
    TrimDurability : `Trim-Durability`,
    OpenAll : `Open All`,
    PlateToughness : `Plate-Toughness`,
    ShaftAmmo : `Shaft-Ammo`,
    Intro4 : `You can use Tinkers' Exporter on any servers or in any modpacks, but Tinkers' Exporter is not responsible for the generated content, nor for any mods, modpacks, servers.`,
    Intro5 : `If you have any play-related questions, please contact the mod author, the modpack author, or the server administrator.`,
    BowAttack : `Bow-Attack`,
    Exclude : `Exclude`,
    RemoveFilters : `Remove Filters`,
    TrimTraits : `Trim-Trais`,
    FullEqual : `Equal`,
    Fletching : `Fletching`,
    EnableThen : `Enable`,
    AllTraits : `All Traits`,
    DataSourceCreateTime : `Data Source Create Time`,
    ListFilters : `List of Filters`,
    QuickSwitch : `Quick Switch`,
    MiningLevel : `Mining Level`,
    CoreDefense : `Core-Defense`,
    Accuracy : `Accuracy`,
    ExtraTraits : `Extra-Traits`,
    CloseAll : `Close All`,
    StringModifier : `String-Modifier`,
    Enable : `Enable`,
    Modifier : `Modifier`,
    Speed : `Speed`,
    Trim : `Trim`,
    HandleModifier : `Handle-Modifier`,
    FletchingTraits : `Fletching-Traits`,
    Data : `Data`,
    AddFilter : `Add Filter`,
    NothingToDisplay : `Nothing to Display`,
    Attack : `Attack`,
    ShaftModifier : `Shaft-Modifier`,
    Defense : `Defense`,
    Plate : `Plate`,
    Ammo : `Ammo`,
    ExperimentalFeatures : `Experimental Features`,
    Toughness : `Toughness`,
    Extra : `Extra`,
    HeadTraits : `Head-Traits`,
    BowTraits : `Bow-Traits`,
    BackToTop : `Back To Top`,
}
